export interface Participant {
    rank: number;
    name: string;
    allPathways: boolean;
    promptDesign: number;
    genAI: number;
    arcade: number;
  }
  
  export const participantsData: Participant[] = [
    {
      rank: 1,
      name: "Shreeti Mohapatra",
      allPathways: true,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 2,
      name: "Sruti Smaranika Kar",
      allPathways: true,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 3,
      name: "Adishree SrikumarI",
      allPathways: true,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 4,
      name: "Pratyasha Panda",
      allPathways: true,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 5,
      name: "Arpita Panda",
      allPathways: true,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 6,
      name: "Animesh Pattnaik",
      allPathways: true,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 7,
      name: "Chirag Agrawal",
      allPathways: true,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 8,
      name: "Kritika Sureka",
      allPathways: true,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 9,
      name: "Khitish Kumar Pradhan",
      allPathways: true,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 10,
      name: "Subham Sworup Mallick",
      allPathways: true,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 11,
      name: "Devansh Bansal",
      allPathways: true,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 12,
      name: "Ritesh Kumar Panda",
      allPathways: true,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 13,
      name: "Vishal Ekka",
      allPathways: true,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 14,
      name: "Ansuman baral",
      allPathways: false,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 15,
      name: "Aditya Hrudaya Sahoo",
      allPathways: false,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 16,
      name: "Ananya Pati",
      allPathways: false,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 17,
      name: "Subham sahoo",
      allPathways: false,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,

    },
    {
      rank: 18,
      name: "Anwesha mishra",
      allPathways: false,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,

    },
    {
      rank: 19,
      name: "Subhalaxmi Nayak",
      allPathways: false,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,

    },
    {
      rank: 20,
      name: "Sai srujana labala",
      allPathways: false,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,

    },
    {
      rank: 21,
      name: "Avilipsha Mishra",
      allPathways: false,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,

    },
    {
      rank: 22,
      name: "Shreya Bastia",
      allPathways: false,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 23,
      name: "Sonakshi Pradhan",
      allPathways: false,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 24,
      name: "Alok kumar sahu",
      allPathways: false,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 25,
      name: "Bharat Panigrahi",
      allPathways: false,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 26,
      name: "Nishant Barik",
      allPathways: false,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 27,
      name: "Rojalin sahu",
      allPathways: false,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 28,
      name: "Hari Shah",
      allPathways: false,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 29,
      name: "Prajnamayee Sahu",
      allPathways: false,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 30,
      name: "Anil Kumar Senapati",
      allPathways: false,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 31,
      name: "Ayush Moharana",
      allPathways: false,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 32,
      name: "K SUPREETHI",
      allPathways: false,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 33,
      name: "Samira Jabin",
      allPathways: false,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 34,
      name: "Srinibas Das",
      allPathways: false,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 35,
      name: "Shibani taria",
      allPathways: false,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 36,
      name: "Ananta Basudev Panigrahi",
      allPathways: false,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 37,
      name: "Ashish Kumar Mishra",
      allPathways: false,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 38,
      name: "Ashish Kumar Mishra",
      allPathways: false,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 39,
      name: "Remit Kumar Patra",
      allPathways: false,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 40,
      name: "Sakalabhaktula Sameer Raja",
      allPathways: false,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    {
      rank: 41,
      name: "Binay Padhan",
      allPathways: false,
      promptDesign: 1,
      genAI: 1,
      arcade: 1,
    },
    
    
    

  ];